name: Backend CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js 22.x
      uses: actions/setup-node@v3
      with:
        node-version: 22.x
        cache: 'npm'
        cache-dependency-path: './backend/package-lock.json'

    - name: Install npm dependencies
      run: npm ci

    - name: Build backend
      run: npm run build --if-present

  docker_push:
    runs-on: ubuntu-latest

    needs: build  # This ensures `docker_push` runs after `build`

    steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build the Docker image
      run: docker build -t domdavis70/comic-backend:latest .
      env:
        COMICVINE_API_KEY: ${{ secrets.COMICVINE_API_KEY }}

    - name: Push the Docker image to Docker Hub
      run: docker push domdavis70/comic-backend:latest

  ecr_push:
    runs-on: ubuntu-latest

    needs: docker_push  # This ensures `ecr_push` runs after `docker_push`

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2  # Change to your desired region

    - name: Log in to Amazon ECR
      run: aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 469782703100.dkr.ecr.us-east-2.amazonaws.com

    - name: Tag Docker image for ECR
      run: docker tag domdavis70/comic-backend:latest 469782703100.dkr.ecr.us-east-2.amazonaws.com/comic-viewer:backend

    - name: Push Docker image to Amazon ECR
      run: docker push 469782703100.dkr.ecr.us-east-2.amazonaws.com/comic-viewer:backend

  # Uncomment the following section when ready to deploy CloudFormation stack
  # deploy_cloudformation:
  #   runs-on: ubuntu-latest

  #   needs: ecr_push  # This ensures `deploy_cloudformation` runs after `ecr_push`

  #   steps:
  #   - name: Configure AWS credentials
  #     uses: aws-actions/configure-aws-credentials@v2
  #     with:
  #       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #       aws-region: us-east-2  # Change to your desired region

  #   - name: Check if CloudFormation stack exists
  #     id: stack-check
  #     run: |
  #       set -e
  #       if aws cloudformation describe-stacks --stack-name my-stack-name; then
  #         echo "Stack exists" 
  #         echo "::set-output name=stack_exists::true"
  #       else
  #         echo "Stack does not exist"
  #         echo "::set-output name=stack_exists::false"
  #       fi

  #   - name: Delete existing CloudFormation stack
  #     if: steps.stack-check.outputs.stack_exists == 'true'
  #     run: |
  #       aws cloudformation delete-stack --stack-name my-stack-name
  #       aws cloudformation wait stack-delete-complete --stack-name my-stack-name

  #   - name: Deploy CloudFormation stack
  #     run: |
  #       aws cloudformation deploy \
  #         --template-file cloudformation-template.yaml \
  #         --stack-name my-stack-name \
  #         --capabilities CAPABILITY_NAMED_IAM
